### ISSUE TITLE
短时间页面加载不出来

### ISSUE THREAD

**Issue by FutureUnreal** [VoAPI/VoAPI#10]
刷新后日志显示
<img width="663" alt="95b44eead903f23f5efae56f4c1e4e0" src="https://github.com/user-attachments/assets/1f6d789e-d990-4118-b9e6-86fd40a4b6f0">
![image](https://github.com/user-attachments/assets/2a8c3234-0511-414f-888c-22bff9066700)
要过几分钟页面才能正常显示

**Comment by Licoy** [comment]
请求速率过快，被限制访问了 429
