### ISSUE TITLE
敏感词是否设置过猛？

### ISSUE THREAD

**Issue by KazeLiu** [VoAPI/VoAPI#6]
[Airota&Nekomoe kissaten][Hyakkano][12][1080p]UpsC].mp4
[DMG][Eromanga Sensei][11][720P][GB].mp4
[DMG][Eromanga Sensei][OVA][01][1080P][BIG5].mp4
[Nekomoe kissaten&LoliHouse] Make Heroine ga Oosugiru!-03 [WebRip 1080p HEVC-10bit AAC ASSx2]
[Nekomoe kissaten&loliHouse] Make Heroine ga Oosugiru! - 12 [WebRip 1080p HEVC-10bit AAC ASSx2]
[Nekomoe kissaten][Make Heroine ga Oosugiru!][12END][1080p]UPTC].mp4
[SBSUB][CONAN][1135][WEBRIP][1080P][HEVC AACJICHS CHT JP](https://app.nextchat.dev/2F704B5A).mkv
[WMSUB][Detective Conan][1133][GB][1080P].mp4
[YunFog][Re Zero kara Hajimeru Isekai Seikatsu S3][02][HEVC][x265 10bit][1080p][JPSC].mp4
[Comicat&Romanticat][Kono Subarashii Sekai ni Shukufuku wo! S3][10][1080P][BIG5&JP][MP4].mp4

Please extract the video titles and episode numbers from the provided data and return them in JSON format. The JSON structure should be as follows:

- For regular episodes: `{"name": "", "episode": x}`
- If a season is mentioned (e.g., "Season 2" or "S2"), include the season number: `{"name": "", "season": y, "episode": x}`
- If the content is a special episode (e.g., OVA or other non-main content), set the season as 0: `{"name": "", "season": 0, "episode": x}`

Only return the JSON output; no additional responses are needed.

![image](https://github.com/user-attachments/assets/72a622c0-d587-4562-8499-7831cab1e2c3)

**Comment by Licoy** [comment]
肯定会存在一些误判，因为敏感词是匹配，不是上下文关联识别，目前无法对此进行优化。
