### ISSUE TITLE
用合格的Github账号或者纯QQ邮箱登录后，调试API时总是出错

### ISSUE THREAD

**Issue by davidxzfei** [VoAPI/VoAPI#7]
我是用github账号登录的，我的github账号是符合API调用要求的(至少1个公共Repo, 3个关注，账号年龄有好几年了。），为啥API调用的时候一直是返回401， 无效的令牌？（我设置过环境变量YOUR_API_KEY)

{
    "error": {
        "message": "[fxszcXPbzxQg3pobN1gB5vBTm1welsqnqcCmeUe1anMNAUfo]无效的令牌 (request id: 2024101522374914827598043818014)",
        "type": "shell_api_error"
    }
}

**Comment by Licoy** [comment]
你的用户名以及调用模型发一下

**Comment by davidxzfei** [comment]
我甚至用了一个纯数字的qq邮箱来测试，仍然是说无效令牌。

**Comment by Licoy** [comment]
这个是上游渠道的问题，这边其他的模型测试没问题，你可以更换个模型试试

**Comment by davidxzfei** [comment]
为什么要急于把所有的issue关闭？这跟模型没有关系，我把URL和令牌加到Dify，直接报无效令牌，还没有选模型呢。

**Comment by Licoy** [comment]
> 为什么要急于把所有的issue关闭？这跟模型没有关系，我把URL和令牌加到Dify，直接报无效令牌，还没有选模型呢。

演示站是仅用于公益调用的，此仓库为项目程序的issue，不建议将公益站的调用问题发送至此，且公益站公告也有说明不提供技术支持。再者就是你上面的回复中有贴出的模型：
<img width="505" alt="image" src="https://github.com/user-attachments/assets/dc5f01b8-01fc-4568-b82f-39fd6f8c92a7">
