### ISSUE TITLE
运行 docker-compose up -d 出现错误提示

### ISSUE THREAD

**Issue by midpoint** [VoAPI/VoAPI#9]
运行 docker-compose up -d 出现错误提示

ERROR: Invalid interpolation format for "healthcheck" option in service "voapi": "wget -q -O - http://localhost:3000/api/status | grep -o '"success":\s*true' | awk -F: '{print $2}'"

**Comment by Licoy** [comment]
什么系统

**Comment by midpoint** [comment]
ubuntu 24

**Comment by Licoy** [comment]
那你启动把healthcheck配置去掉吧
